"""order

Revision ID: 58457c77acd6
Revises: a4780463617e
Create Date: 2022-11-26 18:11:30.043650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58457c77acd6'
down_revision = 'a4780463617e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('delivery', sa.Boolean(), nullable=True),
    sa.Column('adress', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='blx_product'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='blx_user'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_id'))

    op.drop_table('order')
    # ### end Alembic commands ###
