"""1

Revision ID: 933068fbf095
Revises: 
Create Date: 2022-11-23 19:47:22.448678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933068fbf095'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
